version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    environment:
      DATABASE_PASSWORD: postgres
      DATABASE_USER: postgres
      DATABASE_NAME: postgres
      SECRET_KEY: SECRET_KEY
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_started
    command:
      - /bin/bash
      - -c
      - "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000"

volumes:
  pgdata: