version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    image: app:1
    container_name: app
    build:
      dockerfile: ./Dockerfile
    environment:
      DATABASE_PASSWORD: postgres
      DATABASE_USER: postgres
      DATABASE_NAME: postgres
      SECRET_KEY: SECRET_KEY
      MIGRATE: ${MIGRATE:-"false"}
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_started

volumes:
  pgdata:
