version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: db
    environment:
      POSTGRES_PASSWORD: postgres_test
      POSTGRES_USER: postgres_test
      POSTGRES_DB: postgres_test

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    environment:
      DATABASE_PASSWORD: postgres_test
      DATABASE_USER: postgres_test
      DATABASE_NAME: postgres_test
      SECRET_KEY: SECRET_KEY
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_started
    command: ["pytest", "-v", "tests/notes.py"]
